var kmd = {
p001: { id: "p001",
        name: "Schwertfall",
        ventus: "1", aqua: "1", terra: "1",
        cost: "100",
        shop: "1",
        level: "1"
      },
p002: { id: "p002", 
        name: "Schwertfallserie",
        cost: "1200",
        shop: "1",
        level: "1", 
        fusion: {
          1: { mat1: "Schwertfall", lvl1: "3", mat2: "Glücksklinge", lvl2: "3", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "90"},
          2: { mat1: "Barrierensturz", lvl1: "3", mat2: "Wunschklinge", lvl2: "3", type: "P", ventus: "0", aqua: "1", terra: "0", chance: "90"},
          3: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Glücksklinge", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "90"},
        }, 
      },
p003: { id: "p003", 
        name: "Meteorsalve",
        cost: "2500",
        shop: "0",
        level: "3", 
        fusion: { 
          1: { mat1: "Beben", lvl1: "5", mat2: "Schwertfallserie", lvl2: "4", type: "P", ventus: "0", aqua: "0", terra: "1", chance: "100"},
          2: { mat1: "Feuerschlag", lvl1: "3", mat2: "Schmetterklinge", lvl2: "4", type: "D", ventus: "0", aqua: "0", terra: "1", chance: "100"},
        }, 
      }, 
p004: { id: "p004", 
        name: "Zauberstunde",
        cost: "2500",
        shop: "0",
        level: "3",
        fusion: {
          1: { mat1: "Schwertfallserie", lvl1: "4", mat2: "Antigravga", lvl2: "4", type: "O", ventus: "0", aqua: "1", terra: "0", chance: "90"},
          2: { mat1: "Barrierensturz", lvl1: "3", mat2: "Aeroga", lvl2: "4", type: "N", ventus: "0", aqua: "1", terra: "0", chance: "90"},
        },
      }, 
p005: { id: "p005", 
        name: "Sturmlauf",
        ventus: "1", aqua: "1", terra: "1",
        cost: "100",
        shop: "1",
        level: "1",
      },
p006: { id: "p006", 
        name: "Feuersturmlauf",
        cost: "150", 
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Sturmlauf", lvl1: "2", mat2: "Feuer", lvl2: "2", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Sturmlauf", lvl1: "2", mat2: "Feura", lvl2: "2", type: "C", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          3: { mat1: "Verwirrschlag", lvl1: "2", mat2: "Feuer", lvl2: "2", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100"},
        },
      }, 
p007: { id: "p007",
        name: "Dunkler Dunst",
        cost: "1100",
        shop: "1",
        level: "2", 
        fusion: {
          1: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Antigravra", lvl2: "3", type: "D", ventus: "0", aqua: "0", terra: "1", chance: "100"},
          2: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Verdunkeln", lvl2: "3", type: "A", ventus: "0", aqua: "0", terra: "1", chance: "100"},
          3: { mat1: "Feuersturz", lvl1: "3", mat2: "Antigrav", lvl2: "3", type: "C", ventus: "0", aqua: "0", terra: "1", chance: "100"},
        },
      }, 
p008: { id: "p008",
        cost: "2000",
        shop: "1",
        level: "3", 
        name: "Schallschock", 
        fusion: { 
          1: { mat1: "Schwertfallserie", lvl1: "4", mat2: "Dunkler Dunst", lvl2: "4", type: "D", ventus: "0", aqua: "0", terra: "1", chance: "90"},
          2: { mat1: "Schwertfallserie", lvl1: "4", mat2: "Luftgrätsche", lvl2: "4", type: "N", ventus: "1", aqua: "1", terra: "1", chance: "90"},
          3: { mat1: "Feuersturmlauf", lvl1: "4", mat2: "Blitzsturz", lvl2: "4", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "90"},
        },
      }, 
p009: { id: "p009", 
        name: "Chaosschock",
        cost: "2500", 
        shop: "0",
        level: "3",
        fusion: { 
          1: { mat1: "Dunkler Dunst", lvl1: "4", mat2: "Schallschock", lvl2: "5", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "90"},
        }, 
      }, 
p010: { id: "p010", 
        name: "Zantetsuken",
        cost: "1700", 
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Dunkler Dunst", lvl1: "4", mat2: "Stopga", lvl2: "4", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "80"},
          2: { mat1: "Schallschock", lvl1: "5", mat2: "Stopga", lvl2: "4", type: "F", ventus: "0", aqua: "0", terra: "1", chance: "80"},
        },
      }, 
p011: { id: "p011", 
        name: "Schwertwurf",
        cost: "100", 
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "2", mat2: "Sturmlauf", lvl2: "2", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "100"},
        },
      }, 
p012: { id: "p012", 
        name: "Frostwurf",
        cost: "200", 
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Schwertwurf", lvl1: "3", mat2: "Eisra", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Eisklinge", lvl1: "3", mat2: "Fesselschlag", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100"},
        },
      }, 
p013: { id: "p013",
        name: "Schatzwurf",
        cost: "500", 
        shop: "0",
        level: "2",
        fusion: { 
          1: { mat1: "Schwertwurf", lvl1: "3", mat2: "Glücksklinge", lvl2: "3", type: "O", ventus: "1", aqua: "0", terra: "0", chance: "100"},
          2: { mat1: "Glücksklinge", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "K", ventus: "1", aqua: "0", terra: "0", chance: "100"},
          3: { mat1: "Glücksklinge", lvl1: "3", mat2: "Magnet", lvl2: "3", type: "D", ventus: "1", aqua: "0", terra: "0", chance: "100"},
        },
      }, 
p014: { id: "p014",
        name: "Spaltwurf",
        cost: "1300",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Frostwurf", lvl1: "4", mat2: "Magnega", lvl2: "4", type: "J", ventus: "1", aqua: "0", terra: "0", chance: "100"},
          2: { mat1: "Schatzwurf", lvl1: "4", mat2: "Magnega", lvl2: "4", type: "N", ventus: "1", aqua: "0", terra: "0", chance: "100"},
          3: { mat1: "Blitzsturz", lvl1: "4", mat2: "Ausweichrolle", lvl2: "4", type: "P", ventus: "1", aqua: "0", terra: "0", chance: "20"},
          4: { mat1: "Blitzga", lvl1: "4", mat2: "Ausweichrolle", lvl2: "4", type: "L", ventus: "1", aqua: "0", terra: "0", chance: "20"},
          5: { mat1: "Ausweichrolle", lvl1: "4", mat2: "K.-o.-Blocken", lvl2: "3", type: "L", ventus: "1", aqua: "0", terra: "0", chance: "20"},
        },
      }, 
p015: { id: "p015", 
        name: "Multiwurf",
        cost: "1500", 
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Frostwurf", lvl1: "4", mat2: "Aeroga", lvl2: "4", type: "B", ventus: "1", aqua: "0", terra: "0", chance: "100"},
          2: { mat1: "Schatzwurf", lvl1: "4", mat2: "Aeroga", lvl2: "4", type: "F", ventus: "1", aqua: "0", terra: "0", chance: "100"},
        },
      }, 
p016: { id: "p016",
        name: "Feuersturz",
        cost: "650", 
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Entflammen", lvl2: "2", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Feuerschlag", lvl1: "3", mat2: "Feura", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          3: { mat1: "Verwirrschlag", lvl1: "3", mat2: "Feura", lvl2: "3", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          4: { mat1: "Fesselschlag", lvl1: "3", mat2: "Feura", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100"},
        },
      }, 
p017: { id: "p017", 
        name: "Barrierensturz",
        cost: "500",
        shop: "1",
        level: "2", 
        fusion: { 
          1: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Barriere", lvl2: "3", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "100"},
          2: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Barriere", lvl2: "3", type: "K", ventus: "0", aqua: "1", terra: "0", chance: "100"},
        },
      }, 
p018: { id: "p018", 
        name: "Blitzsturz",
        cost: "700",
        shop: "1",
        level: "2", 
        fusion: { 
          1: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Frostwurf", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          3: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          4: { mat1: "Verwirrschlag", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "95"},
        },
      }, 
p019: { id: "p019", 
        name: "Luftstakkato",
        cost: "1500", 
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Sportsfreund", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Feuersturz", lvl1: "3", mat2: "Aero", lvl2: "3", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          3: { mat1: "Feuerschlag", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "C", ventus: "1", aqua: "1", terra: "1", chance: "90"},
        },
      },
p020: { id: "p020",
        name: "Ars Solum",
        cost: "4000",
        shop: "0",
        level: "3", 
        fusion: { 
          1: { mat1: "Sturmlauf", lvl1: "2", mat2: "Blitz", lvl2: "2", type: "K", ventus: "0", aqua: "0", terra: "1", chance: "20"},
          2: { mat1: "Dunkler Dunst", lvl1: "4", mat2: "Schallschock", lvl2: "5", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "20"},
          3: { mat1: "Dunkler Dunst", lvl1: "4", mat2: "Stopga", lvl2: "4", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "20"},
          4: { mat1: "Schallschock", lvl1: "5", mat2: "Stopga", lvl2: "4", type: "K", ventus: "0", aqua: "0", terra: "1", chance: "5"},
          5: { mat1: "Schwertwurf", lvl1: "2", mat2: "Blitz", lvl2: "2", type: "L", ventus: "0", aqua: "0", terra: "1", chance: "5"},
          6: { mat1: "Schwertwurf", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "F", ventus: "0", aqua: "0", terra: "1", chance: "5"},
          7: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "K", ventus: "0", aqua: "0", terra: "1", chance: "5"},
        },
      }, 
p021: { id: "p021", 
        name: "Ars Arcanum",
        cost: "4000",
        shop: "0",
        level: "3", 
        fusion: { 
         1: { mat1: "Schwertfallserie", lvl1: "4", mat2: "Luftstakkato", lvl2: "4", type: "F", ventus: "1", aqua: "0", terra: "0", chance: "100"},
         2: { mat1: "Schwertfall", lvl1: "3", mat2: "Glücksklinge", lvl2: "3", type: "O", ventus: "1", aqua: "0", terra: "0", chance: "10"},
         3: { mat1: "Feuerschlag", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "C", ventus: "1", aqua: "0", terra: "0", chance: "10"},
         4: { mat1: "Schwertfall", lvl1: "2", mat2: "Eis", lvl2: "2", type: "G", ventus: "1", aqua: "0", terra: "0", chance: "5"},
         5: { mat1: "Schwertfall", lvl1: "2", mat2: "Eisra", lvl2: "2", type: "H", ventus: "1", aqua: "0", terra: "0", chance: "5"},
         6: { mat1: "Sturmlauf", lvl1: "2", mat2: "Eis", lvl2: "2", type: "E", ventus: "1", aqua: "0", terra: "0", chance: "5"},
         7: { mat1: "Sturmlauf", lvl1: "2", mat2: "Eisra", lvl2: "2", type: "G", ventus: "1", aqua: "0", terra: "0", chance: "5"},
         8: { mat1: "Giftklinge", lvl1: "2", mat2: "Vitra", lvl2: "2", type: "P", ventus: "1", aqua: "0", terra: "0", chance: "5"},
         9: { mat1: "Eisklinge", lvl1: "2", mat2: "Vitra", lvl2: "2", type: "G", ventus: "1", aqua: "0", terra: "0", chance: "5"},
        }, 
      }, 
p022: { id: "p022", 
        name: "Zeitspleißer",
        cost: "4000", 
        shop: "0",
        level: "3",
        fusion: { 
           1: { mat1: "Barrierensturz", lvl1: "3", mat2: "Wunschklinge", lvl2: "3", type: "P", ventus: "0", aqua: "1", terra: "0", chance: "10"},
           2: { mat1: "Luftstakkato", lvl1: "4", mat2: "Stopga", lvl2: "4", type: "F", ventus: "1", aqua: "0", terra: "0", chance: "100"},
           3: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Glücksklinge", lvl2: "3", type: "K", ventus: "1", aqua: "0", terra: "0", chance: "10"},
           4: { mat1: "Stopga", lvl1: "3", mat2: "Barriere", lvl2: "1", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "20"},
        },
      }, 
p023: { id: "p023", 
        name: "Giftklinge",
        cost: "150", 
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "2", mat2: "Gift", lvl2: "2", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          2: { mat1: "Sturmlauf", lvl1: "2", mat2: "Gift", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          3: { mat1: "Schwertwurf", lvl1: "2", mat2: "Gift", lvl2: "2", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "95"},
        },
      }, 
p024: { id: "p024", 
        name: "Wunschklinge",
        cost: "550", 
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Schwertwurf", lvl1: "2", mat2: "Barrierensturz", lvl2: "2", type: "O", ventus: "0", aqua: "1", terra: "0", chance: "100"},
          2: { mat1: "Barrierensturz", lvl1: "2", mat2: "Betäubungsklinge", lvl2: "2", type: "K", ventus: "0", aqua: "1", terra: "0", chance: "100"},
          3: { mat1: "Betäubungsklinge", lvl1: "2", mat2: "Fesselschlag", lvl2: "2", type: "J", ventus: "0", aqua: "1", terra: "0", chance: "100"},
        },
      }, 
p025: { id: "p025", 
        name: "Eisklinge",
        cost: "1", 
        shop: "200",
        level: "1",
        fusion: {
          1: { mat1: "Schwertfall", lvl1: "2", mat2: "Eis", lvl2: "2", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          2: { mat1: "Schwertfall", lvl1: "2", mat2: "Eisra", lvl2: "2", type: "H", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          3: { mat1: "Sturmlauf", lvl1: "2", mat2: "Eis", lvl2: "2", type: "E", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          4: { mat1: "Sturmlauf", lvl1: "2", mat2: "Eisra", lvl2: "2", type: "E", ventus: "1", aqua: "1", terra: "1", chance: "95"},
        },
      }, 
p026: { id: "p026", 
        name: "Betäubungsklinge",
        cost: "150",
        shop: "1",
        level: "1",
        fusion: {
          1: { mat1: "Sturmlauf", lvl1: "2", mat2: "Blitz", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          2: { mat1: "Schwertwurf", lvl1: "2", mat2: "Blitz", lvl2: "2", type: "L", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          3: { mat1: "Schwertwurf", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "95"},
        },
      }, 
p027: { id: "p027",
        name: "Glücksklinge",
        cost: "700",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Giftklinge", lvl1: "2", mat2: "Vitra", lvl2: "2", type: "P", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          2: { mat1: "Wunschklinge", lvl1: "2", mat2: "Vita", lvl2: "2", type: "O", ventus: "0", aqua: "1", terra: "0", chance: "100"},
          3: { mat1: "Eisklinge", lvl1: "2", mat2: "Vitra", lvl2: "2", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "95"},
          4: { mat1: "Vigra", lvl1: "2", mat2: "LP-Blocken", lvl2: "2", type: "N", ventus: "1", aqua: "0", terra: "1", chance: "90"},
          5: { mat1: "Vigra", lvl1: "2", mat2: "LP-Barriere", lvl2: "2", type: "N", ventus: "0", aqua: "1", terra: "0", chance: "90"},
          6: { mat1: "Vigra", lvl1: "2", mat2: "Fokus-Blocken", lvl2: "2", type: "P", ventus: "1", aqua: "0", terra: "1", chance: "90"},
          7: { mat1: "Vigra", lvl1: "2", mat2: "Fokus-Barriere", lvl2: "2", type: "P", ventus: "0", aqua: "1", terra: "0", chance: "90"},
        },
      }, 
p028: { id: "p028", 
        name: "Feuerschlag",
        cost: "450", 
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Giftklinge", lvl1: "2", mat2: "Feuer", lvl2: "2", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Wunschklinge", lvl1: "2", mat2: "Entflammen", lvl2: "2", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "100"},
          3: { mat1: "Betäubungsklinge", lvl1: "2", mat2: "Feuer", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100"},
        },
      },
p029: { id: "p029",
        name: "Verwirrschlag",
        cost: "450",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "2", mat2: "Verwirren", lvl2: "2", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Sturmlauf", lvl1: "2", mat2: "Antigrav", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          3: { mat1: "Schwertwurf", lvl1: "2", mat2: "Verwirren", lvl2: "2", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "100"},
        },
      },
p030: { id: "p030",
        name: "Fesselschlag",
        cost: "450",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "2", mat2: "Fesseln", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          2: { mat1: "Schwertwurf", lvl1: "2", mat2: "Fesseln", lvl2: "2", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          3: { mat1: "Betäubungsklinge", lvl1: "2", mat2: "Antigrav", lvl2: "2", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100"},
        },
      },
p031: { id: "p031", 
        name: "Tornadoschlag",
        cost: "2700", 
        shop: "0",
        level: "3",
        fusion: { 
          1: { mat1: "Verwirrschlag", lvl1: "3", mat2: "Aeroga", lvl2: "4", type: "G", ventus: "1", aqua: "0", terra: "0", chance: "100"},
          2: { mat1: "Fesselschlag", lvl1: "3", mat2: "Aeroga", lvl2: "4", type: "F", ventus: "1", aqua: "0", terra: "0", chance: "100"},
        },
      },
p032: { id: "p032",
        name: "Schmetterklinge",
        cost: "1800",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Minenfeld", lvl2: "3", type: "O", ventus: "0", aqua: "0", terra: "1", chance: "70"},
          2: { mat1: "Fesselschlag", lvl1: "3", mat2: "Minentrapez", lvl2: "3", type: "L", ventus: "0", aqua: "0", terra: "1", chance: "70"},
        },
      },
p033: { id: "p033",
        name: "Magnetspirale",
        cost: "2300",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "20"},
          2: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "L", ventus: "1", aqua: "1", terra: "1", chance: "20"},
          3: { mat1: "Fesselschlag", lvl1: "3", mat2: "Kollisionsmagnet", lvl2: "4", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          4: { mat1: "Fesselschlag", lvl1: "3", mat2: "Magnega", lvl2: "4", type: "J", ventus: "1", aqua: "1", terra: "1", chance: "100"},
          5: { mat1: "Antigrav", lvl1: "3", mat2: "Magnet", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "20"},
        },
      },
p034: { id: "p034",
        name: "Windschneider",
        cost: "1500",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Verwirrschlag", lvl1: "3", mat2: "Aeroga", lvl2: "4", type: "G", ventus: "0", aqua: "0", terra: "1", chance: "100"},
          2: { mat1: "Fesselschlag", lvl1: "3", mat2: "Aeroga", lvl2: "4", type: "F", ventus: "0", aqua: "0", terra: "1", chance: "100"},
        },
      },
p035: { id: "p035", 
        name: "Grenzsturm",
        cost: "1500", 
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Verwirrschlag", lvl2: "3", type: "G", ventus: "0", aqua: "0", terra: "1", chance: "100"},
          2: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Fesselschlag", lvl2: "3", type: "D", ventus: "0", aqua: "0", terra: "1", chance: "100"},
        },
      },
p036: { id: "p036",
        name: "Erlösung",
        cost: "3000",
        shop: "0",
        level: "3",
        fusion: { 
          1: { mat1: "Multiwurf", lvl1: "5", mat2: "Vigra", lvl2: "4", type: "N", ventus: "1", aqua: "0", terra: "0", chance: "100"},
        },
      },
p037: { id: "p037",
        name: "Kollisionsmagnet",
        cost: "1300",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "80"},
          2: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "L", ventus: "1", aqua: "1", terra: "1", chance: "80"},
          3: { mat1: "Antigravra", lvl1: "3", mat2: "Magnet", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "80"},
        },
      },
p038: { id: "p038",
        name: "Geo-Fall",
        cost: "2100",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Schmetterklinge", lvl2: "4", type: "N", ventus: "0", aqua: "0", terra: "1", chance: "70"},
        },
      },
p039: { id: "p039",
        name: "Selbstopfer",
        cost: "1500",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Dunkler Dunst", lvl1: "4", mat2: "Elimini", lvl2: "5", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "100"},
          2: { mat1: "Giftklinge", lvl1: "3", mat2: "Elimini", lvl2: "5", type: "D", ventus: "0", aqua: "0", terra: "1", chance: "100"},
        },
      },
p040: { id: "p040",
        name: "Auszeit",
        cost: "2400",
        shop: "0",
        level: "2",
        fusion: { 
          1: { mat1: "Vigra", lvl1: "2", mat2: "LP-Blocken", lvl2: "2", type: "N", ventus: "1", aqua: "0", terra: "1", chance: "10"},
          2: { mat1: "Vigra", lvl1: "2", mat2: "LP-Barriere", lvl2: "2", type: "N", ventus: "0", aqua: "1", terra: "0", chance: "10"},
          3: { mat1: "Vigra", lvl1: "2", mat2: "Fokus-Blocken", lvl2: "2", type: "P", ventus: "1", aqua: "0", terra: "1", chance: "10"},
          4: { mat1: "Vigra", lvl1: "2", mat2: "Fokus-Barriere", lvl2: "2", type: "P", ventus: "0", aqua: "1", terra: "0", chance: "10"},
        },
      },
m001: { id: "m001",
        name: "Feuer", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "100",
        shop: "1",
        level: "1",
      },
m002: { id: "m002",
        name: "Feura",
        cost: "500",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Feuersturmlauf", lvl1: "2", mat2: "Feuer", lvl2: "2", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Feuerschlag", lvl1: "2", mat2: "Feuer", lvl2: "2", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Feuer", lvl1: "2", mat2: "Feuer", lvl2: "2", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          4: { mat1: "Feuer", lvl1: "2", mat2: "Entflammen", lvl2: "2", type: "C", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m003: { id: "m003",
        name: "Feuga",
        cost: "1200",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Feuer", lvl2: "3", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          2: { mat1: "Feuer", lvl1: "3", mat2: "Feura", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          3: { mat1: "Feura", lvl1: "3", mat2: "Feura", lvl2: "3", type: "B", ventus: "1", aqua: "1", terra: "1", chance: "90" },
        },
      },
m004: { id: "m004",
        name: "Dunkelfeuga",
        cost: "2000",
        shop: "1",
        level: "2", 
        fusion: { 
          1: { mat1: "Dunkler Dunst", lvl1: "4", mat2: "Feuga", lvl2: "4", type: "D", ventus: "0", aqua: "0", terra: "1", chance: "100" },
          2: { mat1: "Feuga", lvl1: "3", mat2: "Verdunkeln", lvl2: "3", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "100" },
        },
      },
m005: { id: "m005",
        name: "Feuga-Explosion", 
        cost: "1500",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Feura", lvl1: "3", mat2: "Aeroga", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "80" },
          2: { mat1: "Feuga", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "80" },
          3: { mat1: "Feuga", lvl1: "3", mat2: "Aeroga", lvl2: "3", type: "B", ventus: "1", aqua: "1", terra: "1", chance: "80" },
        },
      },
m006: { id: "m006",
        name: "Tripel-Feuga", 
        cost: "1800",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Schwertfallserie", lvl1: "3", mat2: "Feuga", lvl2: "3", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "90" },
          2: { mat1: "Feura", lvl1: "3", mat2: "Feuga", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "95" },
          3: { mat1: "Feuga", lvl1: "3", mat2: "Feuga", lvl2: "3", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "90" },
        },
      },
m007: { id: "m007", 
        name: "Zeitlupen-Feuga",
        cost: "1800",
        shop: "1",
        level: "2", 
        fusion: { 
          1: { mat1: "Feuga", lvl1: "3", mat2: "Gemach", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "80" },
          2: { mat1: "Feuga", lvl1: "3", mat2: "Stopra", lvl2: "3", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "80" },
          3: { mat1: "Feuga", lvl1: "3", mat2: "Stopga", lvl2: "3", type: "B", ventus: "1", aqua: "1", terra: "1", chance: "80" },
        },
      },
m008: { id: "m008", 
        name: "Eis", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "100",
        shop: "1",
        level: "1",
      },
m009: { id: "m009", 
        name: "Eisra",
        cost: "500",
        shop: "1",
        level: "1",
        fusion: {
          1: { mat1: "Schwertwurf", lvl1: "2", mat2: "Eis", lvl2: "2", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Eisklinge", lvl1: "2", mat2: "Eis", lvl2: "2", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Eis", lvl1: "2", mat2: "Eis", lvl2: "2", type: "E", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          4: { mat1: "Eis", lvl1: "2", mat2: "Aero", lvl2: "2", type: "H", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m010: { id: "m010",
        name: "Eisga", 
        cost: "1200",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Eisklinge", lvl1: "3", mat2: "Eisra", lvl2: "3", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Eis", lvl1: "3", mat2: "Eisra", lvl2: "3", type: "E", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Eisra", lvl1: "3", mat2: "Eisra", lvl2: "3", type: "F", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m011: { id: "m011", 
        name: "Tripel-Eisga",
        cost: "1800",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Schwertfallserie", lvl1: "3", mat2: "Eisga", lvl2: "3", type: "G", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Eisra", lvl1: "3", mat2: "Eisga", lvl2: "3", type: "E", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          3: { mat1: "Eisga", lvl1: "3", mat2: "Eisga", lvl2: "3", type: "F", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m012: { id: "m012",
        name: "Blitz",
        ventus: "1", aqua: "1", terra: "1",
        cost: "150",
        shop: "1",
        level: "1",
      },
m013: { id: "m013",
        name: "Blitzra",
        cost: "600",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Betäubungsklinge", lvl1: "2", mat2: "Blitz", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Blitz", lvl1: "2", mat2: "Blitz", lvl2: "2", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Antigrav", lvl1: "2", mat2: "Magnet", lvl2: "2", type: "L", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m014: { id: "m014", 
        name: "Blitzga",
        cost: "1300",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Fesselschlag", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          2: { mat1: "Blitz", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          3: { mat1: "Blitzra", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "J", ventus: "1", aqua: "1", terra: "1", chance: "90" },
        },
      },
m015: { id: "m015",
        name: "Blitzga-Schuss",
        cost: "1500",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Schwertwurf", lvl1: "3", mat2: "Blitzga", lvl2: "3", type: "I", ventus: "0", aqua: "1", terra: "0", chance: "85" },
          2: { mat1: "Feuga", lvl1: "3", mat2: "Blitzga", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "85" },
          3: { mat1: "Frostwurf", lvl1: "3", mat2: "Blitzga", lvl2: "3", type: "E", ventus: "0", aqua: "1", terra: "0", chance: "85" },
        },
      },
m016: { id: "m016",
        name: "Vita", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "150",
        shop: "1",
        level: "1",
      },
m017: { id: "m017",
        name: "Vitra",
        cost: "600",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Blitz", lvl1: "2", mat2: "Vita", lvl2: "2", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Vita", lvl1: "2", mat2: "Vita", lvl2: "2", type: "M", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Vita", lvl1: "2", mat2: "Aero", lvl2: "2", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m018: { id: "m018",
        name: "Vigra",
        cost: "1300",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Vita", lvl1: "3", mat2: "Vitra", lvl2: "3", type: "M", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Vitra", lvl1: "3", mat2: "Vitra", lvl2: "3", type: "N", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m019: { id: "m019",
        name: "Medica",
        cost: "600",
        shop: "1",
        level: "1",
        ventus: "1", aqua: "1", terra: "1" 
      },
m020: { id: "m020",
        name: "Minenfeld",
        cost: "1000",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Feura", lvl1: "3", mat2: "Antigrav", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Feura", lvl1: "3", mat2: "Blocken", lvl2: "1", type: "C", ventus: "1", aqua: "0", terra: "1", chance: "100" },
          3: { mat1: "Entflammen", lvl1: "3", mat2: "Stop", lvl2: "3", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          4: { mat1: "Stopra", lvl1: "", mat2: "Blocken", lvl2: "1", type: "M", ventus: "1", aqua: "0", terra: "1", chance: "100" },
        },
      },
m021: { id: "m021",
        name: "Minentrapez",
        cost: "1000",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Feura", lvl1: "3", mat2: "Stop", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Feura", lvl1: "3", mat2: "Barriere", lvl2: "1", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          3: { mat1: "Aerora", lvl1: "3", mat2: "Entflammen", lvl2: "3", type: "D", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          4: { mat1: "Stopra", lvl1: "3", mat2: "Barriere", lvl2: "1", type: "M", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m022: { id: "m022", 
        name: "Zielsuchmine", 
        cost: "2300",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Minenfeld", lvl1: "4", mat2: "Minentrapez", lvl2: "4", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Minenfeld", lvl1: "4", mat2: "Magnera", lvl2: "4", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          3: { mat1: "Minentrapez", lvl1: "4", mat2: "Magnera", lvl2: "4", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m023: { id: "m023", 
        name: "Antigrav",
        ventus: "1", aqua: "1", terra: "1",
        cost: "150",
        shop: "1",
        level: "1",
      },
m024: { id: "m024",
        name: "Antigravra",
        cost: "600",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Blitz", lvl1: "2", mat2: "Antigrav", lvl2: "2", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          2: { mat1: "Antigrav", lvl1: "2", mat2: "Antigrav", lvl2: "2", type: "M", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          3: { mat1: "Magnet", lvl1: "2", mat2: "Aero", lvl2: "2", type: "P", ventus: "1", aqua: "1", terra: "1", chance: "90" },
        },
      },
m025: { id: "m025",
        name: "Antigravga",
        cost: "1300",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Blitz", lvl1: "3", mat2: "Antigravra", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "80" },
          2: { mat1: "Antigrav", lvl1: "3", mat2: "Antigravra", lvl2: "3", type: "M", ventus: "1", aqua: "1", terra: "1", chance: "80" },
          3: { mat1: "Antigravra", lvl1: "3", mat2: "Antigravra", lvl2: "3", type: "N", ventus: "1", aqua: "1", terra: "1", chance: "80" },
        },
      },
m026: { id: "m026",
        name: "Magnet",
        ventus: "1", aqua: "1", terra: "1",
        cost: "120",
        shop: "1",
        level: "1",
      },
m027: { id: "m027", 
        name: "Magnera",
        cost: "550",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Betäubungsklinge", lvl1: "2", mat2: "Magnet", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Blitz", lvl1: "2", mat2: "Magnet", lvl2: "2", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Magnet", lvl1: "2", mat2: "Magnet", lvl2: "2", type: "M", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m028: { id: "m028",
        name: "Magnega",
        cost: "1250",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Magnet", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Magnera", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "J", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m029: { id: "m029",
        name: "Talermagnet",
        cost: "800",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Wunschklinge", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "K", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Blitzra", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "I", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m030: { id: "m030",
        name: "LP-Magnet",
        cost: "800",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Vita", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "M", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Vitra", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "N", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m031: { id: "m031", 
        name: "D-Link-Magnet",
        cost: "800",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Antigravra", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "L", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Magnera", lvl1: "3", mat2: "Stopra", lvl2: "3", type: "I", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m032: { id: "m032", 
        name: "Aero",
        ventus: "1", aqua: "1", terra: "1",
        cost: "150",
        shop: "1",
        level: "1",
      },
m033: { id: "m033",
        name: "Aerora",
        cost: "600",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "2", mat2: "Aero", lvl2: "2", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "95" },
          2: { mat1: "Blitz", lvl1: "2", mat2: "Aero", lvl2: "2", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "95" },
          3: { mat1: "Aero", lvl1: "2", mat2: "Aero", lvl2: "2", type: "E", ventus: "1", aqua: "1", terra: "1", chance: "95" },
        },
      },
m034: { id: "m034",
        name: "Aeroga",
        cost: "1300",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "O", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          2: { mat1: "Aero", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "M", ventus: "1", aqua: "1", terra: "1", chance: "90" },
          3: { mat1: "Aerora", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "N", ventus: "1", aqua: "1", terra: "1", chance: "90" },
        },
      },
m035: { id: "m035",
        name: "Elimini",
        cost: "1500",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Blitzra", lvl1: "3", mat2: "Antigravra", lvl2: "3", type: "I", ventus: "0", aqua: "0", terra: "1", chance: "20" },
          2: { mat1: "Antigrav", lvl1: "3", mat2: "Antigravra", lvl2: "3", type: "M", ventus: "0", aqua: "0", terra: "1", chance: "20" },
          3: { mat1: "Antigravra", lvl1: "3", mat2: "Antigravra", lvl2: "3", type: "N", ventus: "0", aqua: "0", terra: "1", chance: "20" },
          4: { mat1: "Blitz", lvl1: "2", mat2: "Antigrav", lvl2: "2", type: "I", ventus: "0", aqua: "0", terra: "1", chance: "10" },
          5: { mat1: "Magnet", lvl1: "2", mat2: "Aero", lvl2: "2", type: "P", ventus: "0", aqua: "0", terra: "1", chance: "10" },
          6: { mat1: "Antigrav", lvl1: "2", mat2: "Antigrav", lvl2: "2", type: "M", ventus: "0", aqua: "0", terra: "1", chance: "10" },
        },
      },
m036: { id: "m036",
        name: "Sanctus",
        cost: "400",
        shop: "0",
        level: "3",
        fusion: { 
        1: { mat1: "Multiwurf", lvl1: "5", mat2: "Auszeit", lvl2: "4", type: "N", ventus: "1", aqua: "0", terra: "0", chance: "100" },
        },
      },
m037: { id: "m037", 
        name: "Frost", 
        cost: "2200",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Frostwurf", lvl1: "4", mat2: "Eisga", lvl2: "4", type: "G", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Fesselschlag", lvl1: "3", mat2: "Eisga", lvl2: "4", type: "H", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Eisga", lvl1: "4", mat2: "Tripel-Eisga", lvl2: "4", type: "F", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m038: { id: "m038",
        name: "Gletscherwirbel",
        cost: "2500",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Eisga", lvl1: "4", mat2: "Frost", lvl2: "5", type: "E", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Tripel-Eisga", lvl1: "4", mat2: "Frost", lvl2: "5", type: "F", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m039: { id: "m039", 
        name: "Eisbombardement",
        cost: "1800",
        shop: "1",
        level: "3", 
        fusion: { 
          1: { mat1: "Eisga", lvl1: "4", mat2: "Minenfeld", lvl2: "4", type: "F", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Eisga", lvl1: "4", mat2: "Minentrapez", lvl2: "4", type: "H", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m040: { id: "m040",
        name: "Feuga-Salve",
        cost: "2500",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Feura", lvl1: "3", mat2: "Aeroga", lvl2: "3", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "20" },
          2: { mat1: "Feuga", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "20" },
          3: { mat1: "Feuga", lvl1: "3", mat2: "Aeroga", lvl2: "3", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "20" },
          4: { mat1: "Feuga", lvl1: "3", mat2: "Gemach", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "20" },
          5: { mat1: "Feuga", lvl1: "3", mat2: "Stopra", lvl2: "3", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "20" },
          6: { mat1: "Feuga", lvl1: "3", mat2: "Stopga", lvl2: "3", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "20" },
        },
      },
m041: { id: "m041",
        name: "Feuersturm",
        cost: "3200",
        shop: "0",
        level: "3",
        fusion: { 
          1: { mat1: "Feuga", lvl1: "3", mat2: "Feura", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          2: { mat1: "Feuga", lvl1: "3", mat2: "Feuga", lvl2: "3", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          3: { mat1: "Feuersturz", lvl1: "3", mat2: "Feuerrad", lvl2: "3", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          4: { mat1: "Schwertfallserie", lvl1: "3", mat2: "Feuga", lvl2: "3", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          5: { mat1: "Feuersturmlauf", lvl1: "3", mat2: "Feura", lvl2: "3", type: "D", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          6: { mat1: "Feuer", lvl1: "3", mat2: "Feura", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          7: { mat1: "Feura", lvl1: "3", mat2: "Feura", lvl2: "3", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          8: { mat1: "Feuga-Explosion", lvl1: "4", mat2: "Feuga-Salve", lvl2: "5", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
m042: { id: "m042",
        name: "Tornado",
        cost: "3200",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Schwertfall", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "O", ventus: "1", aqua: "0", terra: "0", chance: "10" },
          2: { mat1: "Blitz", lvl1: "2", mat2: "Aero", lvl2: "2", type: "I", ventus: "1", aqua: "0", terra: "0", chance: "5" },
          3: { mat1: "Magnega", lvl1: "4", mat2: "Aeroga", lvl2: "4", type: "N", ventus: "1", aqua: "0", terra: "0", chance: "100" },
          4: { mat1: "Aero", lvl1: "2", mat2: "Aero", lvl2: "2", type: "E", ventus: "1", aqua: "0", terra: "0", chance: "5" },
          5: { mat1: "Aero", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "M", ventus: "1", aqua: "0", terra: "0", chance: "10" },
          6: { mat1: "Aerora", lvl1: "3", mat2: "Aerora", lvl2: "3", type: "N", ventus: "1", aqua: "0", terra: "0", chance: "10" },
          7: { mat1: "Schwertfall", lvl1: "2", mat2: "Aero", lvl2: "2", type: "G", ventus: "1", aqua: "0", terra: "0", chance: "5" },
        },
      },
m043: { id: "m043", 
        name: "Mega Flare",
        cost: "4000",
        shop: "0",
        level: "3",
        fusion: { 
          1: { mat1: "Feuga-Explosion", lvl1: "4", mat2: "Zeitlupen-Feuga", lvl2: "4", type: "B", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m044: { id: "m044",
        name: "Beben", 
        cost: "2500",
        shop: "1",
        level: "3",
        fusion: { 
          1: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Minenfeld", lvl2: "3", type: "O", ventus: "0", aqua: "0", terra: "1", chance: "30" },
          2: { mat1: "Fesselschlag", lvl1: "3", mat2: "Minentrapez", lvl2: "3", type: "L", ventus: "0", aqua: "0", terra: "1", chance: "30" },
          3: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Schmetterklinge", lvl2: "4", type: "N", ventus: "0", aqua: "0", terra: "1", chance: "30" },
          4: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Antigravga", lvl2: "4", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "90" },
          5: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Magnega", lvl2: "4", type: "C", ventus: "0", aqua: "0", terra: "1", chance: "90" },
        },
      },
m045: { id: "m045",
        name: "Meteo",
        cost: "4000",
        shop: "0",
        level: "3",
        fusion: { 
          1: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Antigravga", lvl2: "4", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "10" },
          2: { mat1: "Schmetterklinge", lvl1: "4", mat2: "Magnega", lvl2: "4", type: "C", ventus: "0", aqua: "0", terra: "1", chance: "10" },
          3: { mat1: "Geo-Fall", lvl1: "5", mat2: "Beben", lvl2: "5", type: "B", ventus: "0", aqua: "0", terra: "1", chance: "100" },
        },
      },
m046: { id: "m046",
        name: "Atmos-Fall",
        cost: "3200",
        shop: "0",
        level: "3",
        fusion: { 
          1: { mat1: "Magnetspirale", lvl1: "5", mat2: "Antigravga", lvl2: "4", type: "J", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m047: { id: "m047",
        name: "Wicht",
        cost: "1500",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Magnera", lvl1: "3", mat2: "Elimini", lvl2: "4", type: "N", ventus: "0", aqua: "0", terra: "1", chance: "100" },
          2: { mat1: "Magnega", lvl1: "4", mat2: "Magnega", lvl2: "4", type: "J", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Magnega", lvl1: "4", mat2: "Fesseln", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m048: { id: "m048",
        name: "Verdunkeln",
        cost: "600",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Antigrav", lvl1: "3", mat2: "Verwirren", lvl2: "3", type: "M", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Antigravra", lvl1: "3", mat2: "Verwirren", lvl2: "3", type: "N", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Antigravra", lvl1: "3", mat2: "Gift", lvl2: "3", type: "P", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m049: { id: "m049",
        name: "Entflammen", 
        cost: "600",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Feuer", lvl1: "3", mat2: "Fesseln", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Feura", lvl1: "3", mat2: "Fesseln", lvl2: "3", type: "C", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m050: { id: "m050",
        name: "Verwirren",
        ventus: "1", aqua: "1", terra: "1", 
        cost: "100",
        shop: "1",
        level: "1",
      },
m051: { id: "m051",
        name: "Fesseln",
        ventus: "1", aqua: "1", terra: "1", 
        cost: "100",
        shop: "1",
        level: "1",
      },
m052: { id: "m052", 
        name: "Gift", 
        ventus: "1", aqua: "1", terra: "1", 
        cost: "100",
        shop: "1",
        level: "1",
      },
m053: { id: "m053",
        name: "Gemach",
        ventus: "1", aqua: "1", terra: "1", 
        cost: "150",
        shop: "1",
        level: "1",
      },
m054: { id: "m054",
        name: "Stop",
        ventus: "1", aqua: "1", terra: "1", 
        cost: "100",
        shop: "1",
        level: "1",
      },
m055: { id: "m055",
        name: "Stopra",
        cost: "500",
        shop: "1",
        level: "1",
        fusion: { 
          1: { mat1: "Gemach", lvl1: "2", mat2: "Gemach", lvl2: "2", type: "L", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Gemach", lvl1: "2", mat2: "Stop", lvl2: "2", type: "K", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          3: { mat1: "Stop", lvl1: "2", mat2: "Stop", lvl2: "2", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m056: { id: "m056",
        name: "Stopga",
        cost: "1200",
        shop: "1",
        level: "2",
        fusion: { 
          1: { mat1: "Stop", lvl1: "3", mat2: "Stopra", lvl2: "3", type: "I", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Stopra", lvl1: "3", mat2: "Stopra", lvl2: "3", type: "J", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
m057: { id: "m057",
        name: "Schlaf",
        ventus: "1", aqua: "1", terra: "1", 
        cost: "100",
        shop: "1",
        level: "1",
      },
a001: { id: "a001",
        name: "Sprung", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
a002: { id: "a002",
        name: "Sportsfreund", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
a003: { id: "a003",
        name: "Ausweichrolle", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
a004: { id: "a004",
        name: "Blitzrolle", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Blitzsturz", lvl1: "4", mat2: "Ausweichrolle", lvl2: "4", type: "P", ventus: "1", aqua: "0", terra: "0", chance: "80" }, 
          2: { mat1: "Blitzga", lvl1: "4", mat2: "Ausweichrolle", lvl2: "4", type: "L", ventus: "1", aqua: "0", terra: "0", chance: "80" }, 
          3: { mat1: "K.-o.-Blocken", lvl1: "3", mat2: "Ausweichrolle", lvl2: "4", type: "L", ventus: "1", aqua: "0", terra: "0", chance: "80" },
        },
      },
a005: { id: "a005",
        name: "Radschlag", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
a006: { id: "a006",
        name: "Feuerrad", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Feuga", lvl1: "4", mat2: "Radschlag", lvl2: "4", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "100" }, 
          2: { mat1: "Feuga-Explosion", lvl1: "4", mat2: "Radschlag", lvl2: "4", type: "B", ventus: "0", aqua: "1", terra: "0", chance: "100" }, 
          3: { mat1: "Feuersturz", lvl1: "3", mat2: "Radschlag", lvl2: "4", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
a007: { id: "a007",
        name: "Luftgrätsche", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
a008: { id: "a008",
        name: "Eisgrätsche", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Eisklinge", lvl1: "3", mat2: "Luftgrätsche", lvl2: "4", type: "F", ventus: "1", aqua: "1", terra: "1", chance: "100" },
          2: { mat1: "Eisga", lvl1: "4", mat2: "Luftgrätsche", lvl2: "4", type: "H", ventus: "1", aqua: "1", terra: "1", chance: "100" },
        },
      },
a009: { id: "a009",
        name: "Schallgrätsche", 
        ventus: "0", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
a010: { id: "a010",
        name: "Grätsche", 
        ventus: "0", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
a011: { id: "a011",
        name: "Stellungsspiel", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
a012: { id: "a012",
        name: "Gleiter", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
a013: { id: "a013",
        name: "Paragleiter", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
a014: { id: "a014",
        name: "Feuergleiter", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Feuersturz", lvl1: "3", mat2: "Gleiter", lvl2: "", type: "C", ventus: "1", aqua: "0", terra: "0", chance: "100" },
          2: { mat1: "Feuga", lvl1: "4", mat2: "Gleiter", lvl2: "", type: "B", ventus: "1", aqua: "0", terra: "0", chance: "100" },
        },
      },
a015: { id: "a015",
        name: "Zielgrätsche", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Sturmlauf", lvl1: "3", mat2: "Magnera", lvl2: "3", type: "P", ventus: "1", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Sturmlauf", lvl1: "3", mat2: "Luftgrätsche", lvl2: "3", type: "C", ventus: "1", aqua: "1", terra: "0", chance: "100" },
          3: { mat1: "Magnet", lvl1: "3", mat2: "Luftgrätsche", lvl2: "3", type: "L", ventus: "1", aqua: "1", terra: "0", chance: "100" },
        },
      },
a016: { id: "a016",
        name: "Teleport", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
a017: { id: "a017",
        name: "Doppelprung", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
d001: { id: "d001",
        name: "Blocken", 
        ventus: "1", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
d002: { id: "d002",
        name: "LP-Blocken", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Vigra", lvl1: "4", mat2: "Blocken", lvl2: "1", type: "P", ventus: "1", aqua: "0", terra: "1", chance: "100" },
          2: { mat1: "Medica", lvl1: "", mat2: "Blocken", lvl2: "1", type: "C", ventus: "1", aqua: "0", terra: "1", chance: "100" },
          },
      },
d003: { id: "d003",
        name: "Fokus-Blocken", 
        ventus: "1", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
d004: { id: "d004",
        name: "K.-o.-Blocken", 
        ventus: "1", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Betäubungsklinge", lvl1: "3", mat2: "Blocken", lvl2: "1", type: "L", ventus: "1", aqua: "0", terra: "1", chance: "100" },
          2: { mat1: "Blitzga", lvl1: "4", mat2: "Blocken", lvl2: "1", type: "I", ventus: "1", aqua: "0", terra: "1", chance: "100" },
          },
      },
d005: { id: "d005",
        name: "Gift-Blocken", 
        ventus: "1", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Giftklinge", lvl1: "3", mat2: "Blocken", lvl2: "1", type: "H", ventus: "1", aqua: "0", terra: "1", chance: "100" },
          2: { mat1: "Gift", lvl1: "3", mat2: "Blocken", lvl2: "1", type: "P", ventus: "1", aqua: "0", terra: "1", chance: "100" },
          },
      },
d006: { id: "d006",
        name: "Barriere", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
d007: { id: "d007",
        name: "LP-Barriere", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Vigra", lvl1: "4", mat2: "Barriere", lvl2: "1", type: "P", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Medica", lvl1: "", mat2: "Barriere", lvl2: "1", type: "N", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          },
      },
d008: { id: "d008",
        name: "Fokus-Barriere", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
d009: { id: "d009",
        name: "Wirr-Barriere", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Verwirrschlag", lvl1: "3", mat2: "Barriere", lvl2: "1", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Verwirren", lvl1: "3", mat2: "Barriere", lvl2: "1", type: "L", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          },
      },
d010: { id: "d010",
        name: "Stopp-Barriere", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Stopga", lvl1: "3", mat2: "Barriere", lvl2: "1", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "80" },
          },
      },
r001: { id: "r001",
        name: "Konterstoß", 
        ventus: "0", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
r002: { id: "r002",
        name: "Rachestreich",
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Sturmlauf", lvl1: "2", mat2: "Konterstoß", lvl2: "2", type: "P", ventus: "0", aqua: "0", terra: "1", chance: "100" },
        },
      },
r003: { id: "r003",
        name: "Konterrausch", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
r004: { id: "r004",
        name: "Rückenhieb", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
r005: { id: "r005",
        name: "Rachewurf", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Sturmlauf", lvl1: "2", mat2: "Schwertwurf", lvl2: "2", type: "P", ventus: "1", aqua: "0", terra: "0", chance: "100" },
        },
      },
r006: { id: "r006",
        name: "Konterknall", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
r007: { id: "r007",
        name: "Rachesturz", 
        cost: "",
        shop: "",
        level: "",
        fusion: { 
          1: { mat1: "Sturmlauf", lvl1: "2", mat2: "Feuersturz", lvl2: "2", type: "C", ventus: "0", aqua: "1", terra: "0", chance: "100" },
          2: { mat1: "Sturmlauf", lvl1: "2", mat2: "Blitzsturz", lvl2: "2", type: "L", ventus: "0", aqua: "1", terra: "0", chance: "100" },
        },
      },
r008: { id: "r008",
        name: "Stehaufmännchen", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s002: { id: "s002",
        name: "Kometenschauer", 
        fusion: { 
          1: { mat1: "Schwertwurf", lvl1: "3", mat2: "Blitzga", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "15" },
          2: { mat1: "Frostwurf", lvl1: "3", mat2: "Blitzga", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "15" },
          3: { mat1: "Feuga", lvl1: "3", mat2: "Blitzga", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "15" },
          4: { mat1: "Schwertfallserie", lvl1: "4", mat2: "Antigravga", lvl2: "4", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "10" },
        },
        cost: "",
        shop: "",
        level: "",
      },
s003: { id: "s003",
        name: "Feuersbrunst", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s004: { id: "s004",
        name: "Irrfeuer", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s005: { id: "s005",
        name: "Düsterhagel", 
        ventus: "0", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s006: { id: "s006",
        name: "Seifenbläser", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
s007: { id: "s007",
        name: "Ragnarök", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s008: { id: "s008",
        name: "Donnerwetter", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s009: { id: "s009",
        name: "Giftschwall", 
        fusion: { 
          1: { mat1: "Giftklinge", lvl1: "3", mat2: "Blocken", lvl2: "1", type: "A", ventus: "1", aqua: "0", terra: "1", chance: "20" },
          1: { mat1: "Gift", lvl1: "3", mat2: "Blocken", lvl2: "1", type: "A", ventus: "1", aqua: "0", terra: "1", chance: "20" },
          1: { mat1: "Schwertfall", lvl1: "2", mat2: "Gift", lvl2: "2", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "5" },
          1: { mat1: "Sturmlauf", lvl1: "2", mat2: "Gift", lvl2: "2", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "5" },
          1: { mat1: "Schwertwurf", lvl1: "2", mat2: "Gift", lvl2: "2", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "5" },
        },
        cost: "",
        shop: "",
        level: "",
      },
s010: { id: "s010",
        name: "Pulsbombe", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
s011: { id: "s011",
        name: "Prismaregen", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
s012: { id: "s012",
        name: "Photonenknall", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s013: { id: "s013",
        name: "Gefrierpunkt", 
        ventus: "1", aqua: "1", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s014: { id: "s014",
        name: "Blitzstrahl", 
        fusion: { 
          1: { mat1: "Schwertfallserie", lvl1: "4", mat2: "Dunkler Dunst", lvl2: "4", type: "A", ventus: "0", aqua: "0", terra: "1", chance: "10" },
          2: { mat1: "Schwertfallserie", lvl1: "4", mat2: "Luftgrätsche", lvl2: "4", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "10" },
          3: { mat1: "Feuersturmlauf", lvl1: "4", mat2: "Blitzsturz", lvl2: "4", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "10" },
          4: { mat1: "Fesselschlag", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "10" },
          5: { mat1: "Blitz", lvl1: "3", mat2: "Blitzra", lvl2: "3", type: "A", ventus: "1", aqua: "1", terra: "1", chance: "10" },
          6: { mat1: "Aeroga", lvl1: "4", mat2: "Blitzsturz", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "10" },
          7: { mat1: "Barrierensturz", lvl1: "4", mat2: "Aeroga", lvl2: "3", type: "A", ventus: "0", aqua: "1", terra: "0", chance: "10" }
        },
        cost: "",
        shop: "",
        level: "",
      },
s015: { id: "s015",
        name: "Schallschatten", 
        ventus: "0", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s016: { id: "s016",
        name: "Ultimakanone", 
        ventus: "0", aqua: "0", terra: "1",
        cost: "",
        shop: "",
        level: "",
      },
s017: { id: "s017",
        name: "Lichtblume", 
        ventus: "0", aqua: "1", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },
s018: { id: "s018",
        name: "Multivortex", 
        ventus: "1", aqua: "0", terra: "0",
        cost: "",
        shop: "",
        level: "",
      },

};

var kristall = {
    A: { leucht: "Pyromanie", zeit: "Magiehast", kraft: "Immunität", energie: "Luftkombo +", luna: "Vitalität", freuden: "Lebensspende", zyklus: "Geselligkeit" },
    B: { leucht: "Pyromanie", zeit: "Notaufladung", kraft: "Abschlussmeister", energie: "Dickschädel", luna: "Esprit", freuden: "Lebensspende", zyklus: "Harte Schule" },
    C: { leucht: "Feuerfest", zeit: "Attackehast", kraft: "Abschlussmeister", energie: "Dickschädel", luna: "Vitalität", freuden: "Lebensspende", zyklus: "Geselligkeit" },
    D: { leucht: "Feuerfest", zeit: "Attackehast", kraft: "Immunität", energie: "Kombo +", luna: "Vitalität", freuden: "Lebensspende", zyklus: "Geselligkeit" },
    E: { leucht: "Eiszeit", zeit: "Magiehast", kraft: "Immunität", energie: "Kombo +", luna: "Heilkunde", freuden: "Lebensspende", zyklus: "Glückspilz" },
    F: { leucht: "Eiszeit", zeit: "Notaufladung", kraft: "Trotzkopf", energie: "Luftkombo +", luna: "Esprit", freuden: "Lebensspende", zyklus: "Glückspilz" },
    G: { leucht: "Frostschutz", zeit: "Attackehast", kraft: "Immunität", energie: "Luftkombo +", luna: "Heilkunde", freuden: "Lebensspende", zyklus: "Glückspilz" },
    H: { leucht: "Frostschutz", zeit: "Magiehast", kraft: "Kombomeister", energie: "Luftkombo +", luna: "Heilkunde", freuden: "Lebensspende", zyklus: "Erfahrungsläufer" },
    I: { leucht: "Gewitter", zeit: "Magiehast", kraft: "Kombomeister", energie: "Luftkombo +", luna: "Vitalität", freuden: "Charmeur", zyklus: "Geselligkeit" },
    J: { leucht: "Gewitter", zeit: "Notaufladung", kraft: "Kombomeister", energie: "Dickschädel", luna: "Defendor", freuden: "Charmeur", zyklus: "Harte Schule" },
    K: { leucht: "Blitzableiter", zeit: "Attackehast", kraft: "Abschlussmeister", energie: "Kombo +", luna: "Vitalität", freuden: "Charmeur", zyklus: "Geselligkeit" },
    L: { leucht: "Blitzableiter", zeit: "Attackehast", kraft: "Abschlussmeister", energie: "Kombo +", luna: "Vitalität", freuden: "Charmeur", zyklus: "Glückspilz" },
    M: { leucht: "Heilkunst", zeit: "Magiehast", kraft: "Kombomeister", energie: "Kombo +", luna: "Heilkunde", freuden: "Charmeur", zyklus: "Glückspilz" },
    N: { leucht: "Heilkunst", zeit: "Notaufladung", kraft: "Trotzkopf", energie: "Kombo +", luna: "Defendor", freuden: "Charmeur", zyklus: "Glückspilz" },
    O: { leucht: "Erhellung", zeit: "Attackehast", kraft: "Abschlussmeister", energie: "Luftkombo +", luna: "Heilkunde", freuden: "Charmeur", zyklus: "Glückspilz" },
    P: { leucht: "Erhellung", zeit: "Magiehast", kraft: "Kombomeister", energie: "Luftkombo +", luna: "Heilkunde", freuden: "Charmeur", zyklus: "Erfahrungsläufer" },
};